---
# https://github.com/digitalist-se/userconsole
- name: Matomo UserConsole present
  git:
    repo: https://github.com/digitalist-se/userconsole.git
    dest: "{{ matomo_html }}/plugins/UserConsole"
    clone: true
    update: true
  become: true
  become_user: "{{ matomo_user }}"
  tags:
    - matomo

- name: UserConsole plugin activated
  shell: "php console --no-ansi -n plugin:activate UserConsole"
  args:
    executable: /bin/bash
    chdir: "{{ matomo_html }}"
  register: matomo_userconsole
  changed_when: '"Activated plugin UserConsole" in matomo_userconsole.stdout'
  become: true
  become_user: "{{ matomo_user }}"
  tags:
    - matomo
...
